begin;
create table public.jd_team_access (email text primary key check (email=lower(email)));
alter table public.jd_team_access enable row level security;
revoke all on public.jd_team_access from anon,authenticated;
grant select on public.jd_team_access to authenticated;
insert into public.jd_team_access(email) values ('judaica.dzn@gmail.com');
create policy team_read_self on public.jd_team_access for select to authenticated using (email=lower((select auth.jwt())->>'email'));
drop policy "public beta read app_state" on public.app_state;
drop policy "public beta insert app_state" on public.app_state;
drop policy "public beta update app_state" on public.app_state;
drop policy "public beta delete app_state" on public.app_state;
revoke all on public.app_state from anon;
grant select,insert,update,delete on public.app_state to authenticated;
create policy jd_team_read on public.app_state for select to authenticated using (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false);
create policy jd_team_insert on public.app_state for insert to authenticated with check (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false);
create policy jd_team_update on public.app_state for update to authenticated using (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false) with check (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false);
create policy jd_team_delete on public.app_state for delete to authenticated using (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false);
drop policy jd_assets_public_read on storage.objects;
drop policy jd_assets_public_insert on storage.objects;
drop policy jd_assets_public_update on storage.objects;
drop policy jd_assets_public_delete on storage.objects;
create policy jd_assets_team_read on storage.objects for select to authenticated using (bucket_id='jd-assets' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_assets_team_insert on storage.objects for insert to authenticated with check (bucket_id='jd-assets' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_assets_team_update on storage.objects for update to authenticated using (bucket_id='jd-assets' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false)) with check (bucket_id='jd-assets' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_assets_team_delete on storage.objects for delete to authenticated using (bucket_id='jd-assets' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
drop policy jd_quotes_public_read on storage.objects;
drop policy jd_quotes_public_insert on storage.objects;
drop policy jd_quotes_public_update on storage.objects;
drop policy jd_quotes_public_delete on storage.objects;
create policy jd_quotes_team_read on storage.objects for select to authenticated using (bucket_id='jd-quotes' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_quotes_team_insert on storage.objects for insert to authenticated with check (bucket_id='jd-quotes' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_quotes_team_update on storage.objects for update to authenticated using (bucket_id='jd-quotes' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false)) with check (bucket_id='jd-quotes' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
create policy jd_quotes_team_delete on storage.objects for delete to authenticated using (bucket_id='jd-quotes' and (exists (select 1 from public.jd_team_access t where t.email = lower((select auth.jwt())->>'email')) and coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)=false));
update storage.buckets set public=false where id in ('jd-assets','jd-quotes');
commit;
